### ISSUE TITLE
Input file format?

### ISSUE THREAD

**Issue by akrejczinger** [tehmaze/diagram#16]
From the provided pictures it's not clear to me what format the input data is expected to be in. Tab separated? CSV? Something custom?
I'm also not familiar with the `./bin/random` command used in the examples.

EDIT: I found the random command in the repo. I think it would still help if an input file was shown in the examples.
Also is there a way to have pairs of (x,y) points in the data?

**Comment by tehmaze** [comment]
The rows are formed by newlines, the columns by spaces.
