### ISSUE TITLE
Issues with graphing key,value data

### ISSUE THREAD

**Issue by WillieStevenson** [tehmaze/diagram#21]
Hi. This is a great project and I usually use it to plot stock movement. However, I have issues plotting key,value data.

I have data that looks like so:
```
1/31/2019, 2200.00
1/15/2019, 3285.78
3/29/2019, 4062.78
3/15/2019, 2462.79
5/15/2019, 6596.66
```

I pipe this data to `diagram -H -a -k -p gray`, but it doesn't seem to work. Am I doing something wrong? I get the following error:
`ValueError: zero-size array to reduction operation minimum which has no identity`

Thanks for the help in advance.

**Comment by tehmaze** [comment]
Diagram doesn't support horizontal labels, so if you want to graph data points with a non-fixed horizontal axis you will have to do the interpolation yourself.
