### ISSUE TITLE
Diagram graphs not shown properly

### ISSUE THREAD

**Issue by Zdenek-KIncl** [tehmaze/diagram#23]
In CLI mode run in BASH the tool does not run properly:

Example 1:
for n in {10..20}; do echo -e "$n\n"; done | diagram -H -x 5

probably rounding error down, the third bar is shorten than second and non-monotonicity is visible. 
+10+20
▋    
█    
▋    
██   
██▋  
███  
███▋ 
████ 
████▋
█████

Example 2:
for n in {10..20}; do echo -e "$n\n"; done | diagram -V

at my side look more like right-aligned horizontal bar graph

+20    ██████████
            █████████
               ████████
                  ███████
                    ██████
                      █████
                        ████
                           ███
                              ██
+10                          █
        
   
GNU bash, version 4.3.11(1)-release (i686-pc-linux-gnu)
LXTerminal

**Comment by gbinside** [comment]
https://github.com/tehmaze/diagram/pull/25
